-- 코드를 작성해주세요
WITH CODE AS (
SELECT CODE
FROM SKILLCODES
WHERE CATEGORY = 'Front End')
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM CODE AS A INNER JOIN DEVELOPERS AS B ON A.CODE & B.SKILL_CODE
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID;