-- 코드를 입력하세요
WITH MILK AS (
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Milk'),
YOGURT AS (
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Yogurt')
SELECT DISTINCT A.CART_ID
FROM MILK AS A INNER JOIN YOGURT AS B ON A.CART_ID = B.CART_ID
ORDER BY A.CART_ID