-- 코드를 입력하세요
WITH ID AS (
SELECT MEMBER_ID, COUNT(*) AS CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY CNT DESC
LIMIT 1),
MEMBER AS (
SELECT REST_REVIEW.MEMBER_ID, ID.CNT
FROM REST_REVIEW, ID
GROUP BY REST_REVIEW.MEMBER_ID
HAVING COUNT(REST_REVIEW.MEMBER_ID) = ID.CNT)
SELECT C.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS A INNER JOIN MEMBER AS B
ON A.MEMBER_ID = B.MEMBER_ID
INNER JOIN MEMBER_PROFILE AS C
ON B.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;