-- 코드를 입력하세요
SELECT A.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY,
    SUM(A.PRICE * B.SALES) AS TOTAL_SALES
FROM BOOK AS A INNER JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
    INNER JOIN AUTHOR AS C ON A.AUTHOR_ID = C.AUTHOR_ID
WHERE SALES_DATE LIKE '2022-01-%'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;