-- 코드를 작성해주세요
SELECT
    CONCAT(CASE
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%c') < 4 THEN 1
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%c') < 7 THEN 2
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%c') < 10 THEN 3
        ELSE 4
    END, 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;