-- 코드를 입력하세요
WITH MAX_CATEGORY AS
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
GROUP BY CATEGORY)
SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT AS A INNER JOIN MAX_CATEGORY AS B ON A.PRICE = B.MAX_PRICE
GROUP BY CATEGORY
HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;