-- 코드를 입력하세요
WITH CS_N AS
(SELECT *
FROM APPOINTMENT
WHERE APNT_YMD LIKE '2022-04-13%' AND MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N')
SELECT B.APNT_NO, A.PT_NAME, A.PT_NO, B.MCDP_CD, C.DR_NAME, B.APNT_YMD
FROM PATIENT AS A INNER JOIN CS_N AS B ON A.PT_NO = B.PT_NO
    INNER JOIN DOCTOR AS C ON B.MDDR_ID = C.DR_ID
ORDER BY B.APNT_YMD;