-- 코드를 입력하세요
WITH SUM_SALES AS
(SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES
WHERE SALES_DATE LIKE '2022-01-%'
GROUP BY BOOK_ID
ORDER BY BOOK_ID)
SELECT A.CATEGORY, SUM(B.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK AS A INNER JOIN SUM_SALES AS B ON A.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY;