-- 코드를 입력하세요
WITH HISTORY AS (
    SELECT B.HISTORY_ID, A.DAILY_FEE, DATEDIFF(B.END_DATE, B.START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_CAR AS A INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '트럭')
SELECT HISTORY_ID,
    CASE
        WHEN DURATION >= 90 THEN ROUND(DAILY_FEE * 0.85 * DURATION)
        WHEN DURATION >= 30 THEN ROUND(DAILY_FEE  * 0.92 * DURATION)
        WHEN DURATION >= 7 THEN ROUND(DAILY_FEE  * 0.95 * DURATION)
        ELSE ROUND(DAILY_FEE * DURATION)
    END AS FEE
FROM HISTORY
ORDER BY FEE DESC, HISTORY_ID DESC;