-- 코드를 입력하세요
WITH MAX_FAVORITES AS
(SELECT MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE)
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO AS A INNER JOIN MAX_FAVORITES AS B ON A.FAVORITES = B.FAVORITES
GROUP BY A.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC;