-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV;

# WITH MAX_SIZE AS
# (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
# FROM ECOLI_DATA
# GROUP BY YEAR)
# SELECT B.YEAR, (MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, ID
# FROM ECOLI_DATA AS A INNER JOIN MAX_SIZE AS B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
# ORDER BY YEAR, YEAR_DEV

# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(DIFFERENTIATION_DATE) = YEAR) - SIZE_OF_COLONY AS YEAR_DEV, ID
# FROM ECOLI_DATA
# ORDER BY YEAR, YEAR_DEV;