-- 코드를 입력하세요
# SELECT 
#     CASE
#         WHEN PRODUCT_CODE LIKE 'A1%' THEN 'A1'
#         WHEN PRODUCT_CODE LIKE 'C3%' THEN 'C3'
#         WHEN PRODUCT_CODE LIKE 'K1%' THEN 'K1'
#     END AS CATEGORY, COUNT(*) AS PRODUCTS
# FROM PRODUCT
# GROUP BY CATEGORY
# ORDER BY CATEGORY;

SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;