-- 코드를 입력하세요
WITH SUM_SALES AS
(SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000)
SELECT B.USER_ID, B.NICKNAME, A.TOTAL_SALES
FROM SUM_SALES AS A INNER JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
ORDER BY TOTAL_SALES;
